---
title: "Assigment.QFISH"
output: html_document
date: "2023-05-04"
Author: Hanna Shrubshall 
---

##Assignment. ENd-to-end data analysis in R 
The following code is for the assignment using data from QFISH. 
*Note to self remember when copying path of file that the \ have to be changed to /

```{r}
#linking the code to my GitHub repository 
library(usethis)
use_git_config(user.name = "hanna-shrubshall", user.email = "hanna.shrubshall@gmail.com")


#install and load packages 
#install.packages(tidyverse)
#install.packages(scales)
#install.packages("ggridges")
install.packages("tmap")
library(tidyverse)
library(ggplot2)
library(scales)
library(ggridges)
library(RColorBrewer)
library(tmap)
```

```{r}
#read in the data
df <- read_csv("C:/Users/Adam/Desktop/github (1)/github/MB5370-Assignmet/data/Sharks.csv", col_names = FALSE)

#pivoting the table so that the years are all in one column 
years <- df |> filter(X2 == 2001) |> pivot_longer(everything()) |> 
  select(value) |> rename(Year = value) |> 
  mutate(Year = case_when(!str_detect(Year, "Total") ~ Year)) |>
  drop_na(Year) |> 
  unique()

#Puts all the species into a column 
animal <- df |> filter(X2 == "Mammal")|> pivot_longer(everything()) |> 
  select(value) |> rename(Species = value) |> 
  unique() |> 
  mutate(Species = case_when(is.na(Species) ~ "Total",
                                         T ~ Species)) |>
  filter(Species != "Area")

#Relocationg row
animal <- animal |> slice(-3) |> bind_rows(animal |> slice(3))

#Merging the animals with the years into a tidy dataset
animal_year <- merge(animal, years)

#Changing the name of the first column to Area and changing the title of Grand Total to Location Grand Total 
area <- df |> select(1) |> filter(!row_number() %in% c(1:3)) |> 
  rename(Location = X1) |> 
  mutate(Location = case_when(Location == "Grand Total" ~ "Location_Grand_Total",
                          T ~ Location))

#Merging the Area with 
animal_year_area <- merge(area, animal_year) |> mutate(Location = as.factor(Location)) |> 
  arrange(ordered(Location,
                  levels = c("Bribie Island", "Bundaberg", "Cairns", "Capricorn Coast",
                             "Gladstone", "Gold Coast", "Mackay", "Nth Stradbroke Is.",
                             "Rainbow Beach", "Sunshine Coast North", "Sunshine Coast South",
                             "Sunshine Coast South & Bribie Island", "Townsville", "Area_Grand_Total")))


#This makes the species count tidier and skips the first two rows as they are not relevant information 
observations  <- df |> select(2:ncol(df)) |> filter(!row_number() %in% c(1, 2, 3)) |> 
  select(!last_col()) |> 
  select(where(~!all(is.na(.x)))) |> pivot_longer(everything(), names_to = "names", values_to = "values") |> 
  select(!names)

#This combines all the variables into a tidy table 
all_observations <- cbind(animal_year_area, observations) |> mutate(values = as.numeric(values),
                                                                    Year = as.numeric(Year))

#Calculates the total number of observations for each location 
grand_total <- df |> filter(!row_number() %in% c(1, 2, 3)) |> 
  select(1,last_col()) |> 
  rename(Location = X1, Total_number_of_observations = X118) |> 
  mutate(Location = case_when(Location == "Grand Total" ~ "Location_Grand_Total",
                          T ~ Location))
```


```{r}
#Creating plots 
ggplot(filter(all_observations, Location != "Location_Grand_Total")) +
  geom_line(aes(x = Year, y = values, group = Species, colour = Species)) +   facet_wrap(~Location, nrow = 4)

ggplot(filter(all_observations, Location != "Location_Grand_Total")) +
  geom_line(aes(x = Year, y = values, group = Species, colour = Species)) +
  facet_grid(~Location, vars(Species))+
theme( legend.position="bottom",
        legend.title=element_blank(),
        legend.text=element_text(size=8),
       legend.background = element_rect(fill = NULL),
        strip.background = element_rect(colour="black",
                                        fill="white"),
      panel.border = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(), 
      panel.grid.major.x = element_blank(), 
      panel.grid.major.y = element_line(colour = "black"))


```

```{r}
#trying to make the plots horizontal

test <- all_observations %>% filter(Species != "Total")

Sharks <- ggplot(filter(test, Location != "Location_Grand_Total")) +
  geom_point(aes(x = Year, y = values, group = Species, colour = Species))+  facet_wrap(~Location, nrow = 4) 
Sharks
       
```


```{r}
Sharks + facet_wrap(~Location, scales = "fixed", ncol = 2) + 
  theme(panel.background = element_rect(fill = "white"),
 legend.key = element_rect(fill = "white"),
 legend.position = "bottom",
 legend.title = element_text(face = "bold"), 
 axis.text.x = element_text(face="bold", 
                           size=8, angle=45),
          axis.text.y = element_text(face="bold",  
                           size=8, angle=45), 
panel.grid.major = element_line(color = "grey",
                                        size = 0.25,
                                        linetype = 1)) +
  theme_classic()
```

```{r}
#making a boxplot in R 
```


```{r}
#inputting data on t_map
#this creates the map of Australia 
tm_shape("Sharks") + 
  tm_polygons("Sharks")

#bbox expands the extent of the map so all data points are detected 
tmap_mode("view")+
tm_shape(shelf, bbox = sdat) +
   tm_borders("white", lwd = .5)
  tm_shape(aus) + 
  tm_polygons(alpha = 0, border.alpha = 1) + 
  tm_shape(sdat) + 
  tm_dots(col = "route")+
    tm_basemap("Esri.WorldImagery") +  tm_tiles("Stamen.TonerLabels", ) 
```

